
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainVogWPF.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(746, 487)
        MainWindow.setMinimumSize(QSize(746, 487))
        MainWindow.setMaximumSize(QSize(746, 487))
        icon = QIcon()
        icon.addFile(u":/icons/icons/Juice_Icons_FREE_Pack/32x32/Briefcase.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"background-color: #033E63;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 741, 441))
        self.login = QWidget()
        self.login.setObjectName(u"login")
        self.frame_4 = QFrame(self.login)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(350, 30, 381, 391))
        self.frame_4.setStyleSheet(u"background-color: white\n"
"")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.login_label_header = QLabel(self.frame_4)
        self.login_label_header.setObjectName(u"login_label_header")
        self.login_label_header.setGeometry(QRect(40, 10, 321, 51))
        self.login_label_header.setStyleSheet(u"background-color: white;\n"
"color: black;\n"
"font-size: 30px;")
        self.login_label_header.setAlignment(Qt.AlignCenter)
        self.login_text_username = QLineEdit(self.frame_4)
        self.login_text_username.setObjectName(u"login_text_username")
        self.login_text_username.setGeometry(QRect(40, 100, 321, 41))
        font = QFont()
        font.setPointSize(12)
        self.login_text_username.setFont(font)
        self.login_text_username.setStyleSheet(u"background-color: white;\n"
"color: black;")
        self.login_text_password = QLineEdit(self.frame_4)
        self.login_text_password.setObjectName(u"login_text_password")
        self.login_text_password.setGeometry(QRect(40, 160, 321, 41))
        self.login_text_password.setFont(font)
        self.login_text_password.setStyleSheet(u"background-color: white;\n"
"color: black;")
        self.login_text_password.setEchoMode(QLineEdit.Password)
        self.login_btn_Sign_In = QPushButton(self.frame_4)
        self.login_btn_Sign_In.setObjectName(u"login_btn_Sign_In")
        self.login_btn_Sign_In.setGeometry(QRect(40, 220, 321, 41))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(3, 62, 99, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 128))
        brush2.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush3 = QBrush(QColor(255, 255, 255, 128))
        brush3.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush4 = QBrush(QColor(255, 255, 255, 128))
        brush4.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush4)
#endif
        self.login_btn_Sign_In.setPalette(palette)
        self.login_btn_Sign_In.setFont(font)
        self.login_btn_Sign_In.setStyleSheet(u"background-color: #033E63;\n"
"color: white;")
        self.login_label_login_denied = QLabel(self.frame_4)
        self.login_label_login_denied.setObjectName(u"login_label_login_denied")
        self.login_label_login_denied.setGeometry(QRect(40, 280, 321, 16))
        self.login_label_login_denied.setStyleSheet(u"background-color: white;\n"
"color: black;\n"
"font-size: 14px;\n"
"")
        self.label = QLabel(self.login)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 70, 241, 321))
        self.label.setPixmap(QPixmap(u":/images/images/compaylogo.png"))
        self.label.setScaledContents(True)
        self.line = QFrame(self.login)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(310, 20, 21, 411))
        self.line.setStyleSheet(u"")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.stackedWidget.addWidget(self.login)
        self.main = QWidget()
        self.main.setObjectName(u"main")
        self.menu_frame = QFrame(self.main)
        self.menu_frame.setObjectName(u"menu_frame")
        self.menu_frame.setGeometry(QRect(350, 30, 381, 391))
        self.menu_frame.setStyleSheet(u"background-color: white\n"
"")
        self.menu_frame.setFrameShape(QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QFrame.Raised)
        self.menu_label_title = QLabel(self.menu_frame)
        self.menu_label_title.setObjectName(u"menu_label_title")
        self.menu_label_title.setGeometry(QRect(40, 10, 321, 51))
        self.menu_label_title.setStyleSheet(u"background-color: white;\n"
"color: black;\n"
"font-size: 30px;")
        self.menu_label_title.setAlignment(Qt.AlignCenter)
        self.menu_label_header = QLabel(self.menu_frame)
        self.menu_label_header.setObjectName(u"menu_label_header")
        self.menu_label_header.setGeometry(QRect(40, 70, 311, 21))
        self.menu_label_header.setStyleSheet(u"font-size: 16px;\n"
"background-color: white;\n"
"color: black;")
        self.menu_list = QListWidget(self.menu_frame)
        QListWidgetItem(self.menu_list)
        QListWidgetItem(self.menu_list)
        QListWidgetItem(self.menu_list)
        QListWidgetItem(self.menu_list)
        QListWidgetItem(self.menu_list)
        self.menu_list.setObjectName(u"menu_list")
        self.menu_list.setGeometry(QRect(40, 110, 321, 201))
        self.menu_list.setStyleSheet(u"font-size:14px;\n"
"background-color: white;\n"
"color: black;")
        self.menu_btn_submit = QPushButton(self.menu_frame)
        self.menu_btn_submit.setObjectName(u"menu_btn_submit")
        self.menu_btn_submit.setGeometry(QRect(40, 330, 321, 41))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush5 = QBrush(QColor(255, 255, 255, 128))
        brush5.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush6 = QBrush(QColor(255, 255, 255, 128))
        brush6.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush6)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush7 = QBrush(QColor(255, 255, 255, 128))
        brush7.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush7)
#endif
        self.menu_btn_submit.setPalette(palette1)
        self.menu_btn_submit.setFont(font)
        self.menu_btn_submit.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.line_2 = QFrame(self.main)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(310, 20, 21, 411))
        self.line_2.setStyleSheet(u"")
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_2 = QLabel(self.main)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 70, 241, 321))
        self.label_2.setPixmap(QPixmap(u":/images/images/compaylogo.png"))
        self.label_2.setScaledContents(True)
        self.stackedWidget.addWidget(self.main)
        self.client_list = QWidget()
        self.client_list.setObjectName(u"client_list")
        self.list_client_list = QListWidget(self.client_list)
        self.list_client_list.setObjectName(u"list_client_list")
        self.list_client_list.setGeometry(QRect(50, 150, 321, 191))
        self.list_client_list.setStyleSheet(u"font-size:14px;\n"
"background-color: white;\n"
"color: black;")
        self.frame = QFrame(self.client_list)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 30, 711, 391))
        self.frame.setStyleSheet(u"background-color: white\n"
"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.client_list_label_title = QLabel(self.frame)
        self.client_list_label_title.setObjectName(u"client_list_label_title")
        self.client_list_label_title.setGeometry(QRect(20, 10, 671, 51))
        self.client_list_label_title.setStyleSheet(u"background-color: white;\n"
"color: black;\n"
"font-size: 30px;")
        self.client_list_label_title.setAlignment(Qt.AlignCenter)
        self.client_list_btn_main = QPushButton(self.frame)
        self.client_list_btn_main.setObjectName(u"client_list_btn_main")
        self.client_list_btn_main.setGeometry(QRect(510, 330, 181, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush8 = QBrush(QColor(255, 255, 255, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush9 = QBrush(QColor(255, 255, 255, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush10 = QBrush(QColor(255, 255, 255, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.client_list_btn_main.setPalette(palette2)
        self.client_list_btn_main.setFont(font)
        self.client_list_btn_main.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.client_list_list = QTableView(self.frame)
        self.client_list_list.setObjectName(u"client_list_list")
        self.client_list_list.setGeometry(QRect(20, 81, 671, 231))
        self.stackedWidget.addWidget(self.client_list)
        self.client_list_edit = QWidget()
        self.client_list_edit.setObjectName(u"client_list_edit")
        self.frame_2 = QFrame(self.client_list_edit)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(20, 30, 711, 391))
        self.frame_2.setStyleSheet(u"background-color: white\n"
"")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.client_list_edit_label_title = QLabel(self.frame_2)
        self.client_list_edit_label_title.setObjectName(u"client_list_edit_label_title")
        self.client_list_edit_label_title.setGeometry(QRect(20, 10, 671, 51))
        self.client_list_edit_label_title.setStyleSheet(u"background-color: white;\n"
"color: black;\n"
"font-size: 30px;")
        self.client_list_edit_label_title.setAlignment(Qt.AlignCenter)
        self.client_list_edit_btn_main = QPushButton(self.frame_2)
        self.client_list_edit_btn_main.setObjectName(u"client_list_edit_btn_main")
        self.client_list_edit_btn_main.setGeometry(QRect(510, 330, 181, 41))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush11 = QBrush(QColor(255, 255, 255, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush12 = QBrush(QColor(255, 255, 255, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush13 = QBrush(QColor(255, 255, 255, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
#endif
        self.client_list_edit_btn_main.setPalette(palette3)
        self.client_list_edit_btn_main.setFont(font)
        self.client_list_edit_btn_main.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.client_list_edit_btn_edit = QPushButton(self.frame_2)
        self.client_list_edit_btn_edit.setObjectName(u"client_list_edit_btn_edit")
        self.client_list_edit_btn_edit.setGeometry(QRect(320, 330, 181, 41))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush14 = QBrush(QColor(255, 255, 255, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush14)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush15 = QBrush(QColor(255, 255, 255, 128))
        brush15.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush15)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush16 = QBrush(QColor(255, 255, 255, 128))
        brush16.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush16)
#endif
        self.client_list_edit_btn_edit.setPalette(palette4)
        self.client_list_edit_btn_edit.setFont(font)
        self.client_list_edit_btn_edit.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.client_list_edit_list = QTableView(self.frame_2)
        self.client_list_edit_list.setObjectName(u"client_list_edit_list")
        self.client_list_edit_list.setGeometry(QRect(20, 81, 671, 231))
        self.client_list_edit_enter_id = QLineEdit(self.frame_2)
        self.client_list_edit_enter_id.setObjectName(u"client_list_edit_enter_id")
        self.client_list_edit_enter_id.setGeometry(QRect(220, 330, 91, 41))
        self.client_list_edit_enter_id.setFont(font)
        self.client_list_edit_enter_id.setStyleSheet(u"background-color: white;\n"
"color: black;")
        self.stackedWidget.addWidget(self.client_list_edit)
        self.client_edit_profile = QWidget()
        self.client_edit_profile.setObjectName(u"client_edit_profile")
        self.frame_3 = QFrame(self.client_edit_profile)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(20, 30, 711, 391))
        self.frame_3.setStyleSheet(u"background-color: white\n"
"")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.client_edit_profile_title = QLabel(self.frame_3)
        self.client_edit_profile_title.setObjectName(u"client_edit_profile_title")
        self.client_edit_profile_title.setGeometry(QRect(20, 10, 671, 51))
        self.client_edit_profile_title.setStyleSheet(u"background-color: white;\n"
"color: black;\n"
"font-size: 30px;")
        self.client_edit_profile_title.setAlignment(Qt.AlignCenter)
        self.client_edit_profile_btn_update = QPushButton(self.frame_3)
        self.client_edit_profile_btn_update.setObjectName(u"client_edit_profile_btn_update")
        self.client_edit_profile_btn_update.setGeometry(QRect(320, 330, 181, 41))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush17 = QBrush(QColor(255, 255, 255, 128))
        brush17.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush17)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush18 = QBrush(QColor(255, 255, 255, 128))
        brush18.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush18)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush19 = QBrush(QColor(255, 255, 255, 128))
        brush19.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush19)
#endif
        self.client_edit_profile_btn_update.setPalette(palette5)
        self.client_edit_profile_btn_update.setFont(font)
        self.client_edit_profile_btn_update.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.client_edit_profile_btn_cancel = QPushButton(self.frame_3)
        self.client_edit_profile_btn_cancel.setObjectName(u"client_edit_profile_btn_cancel")
        self.client_edit_profile_btn_cancel.setGeometry(QRect(510, 330, 181, 41))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush20 = QBrush(QColor(255, 255, 255, 128))
        brush20.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush20)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush21 = QBrush(QColor(255, 255, 255, 128))
        brush21.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush21)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush22 = QBrush(QColor(255, 255, 255, 128))
        brush22.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush22)
#endif
        self.client_edit_profile_btn_cancel.setPalette(palette6)
        self.client_edit_profile_btn_cancel.setFont(font)
        self.client_edit_profile_btn_cancel.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.client_edit_profile_list = QTableView(self.frame_3)
        self.client_edit_profile_list.setObjectName(u"client_edit_profile_list")
        self.client_edit_profile_list.setGeometry(QRect(20, 80, 671, 71))
        self.client_edit_profile_first_name = QLineEdit(self.frame_3)
        self.client_edit_profile_first_name.setObjectName(u"client_edit_profile_first_name")
        self.client_edit_profile_first_name.setGeometry(QRect(320, 170, 371, 41))
        self.client_edit_profile_first_name.setFont(font)
        self.client_edit_profile_first_name.setStyleSheet(u"background-color: white;\n"
"color: black;")
        self.client_edit_profile_last_name = QLineEdit(self.frame_3)
        self.client_edit_profile_last_name.setObjectName(u"client_edit_profile_last_name")
        self.client_edit_profile_last_name.setGeometry(QRect(320, 220, 371, 41))
        self.client_edit_profile_last_name.setFont(font)
        self.client_edit_profile_last_name.setStyleSheet(u"background-color: white;\n"
"color: black;")
        self.client_edit_profile_cmb_service = QComboBox(self.frame_3)
        self.client_edit_profile_cmb_service.addItem("")
        self.client_edit_profile_cmb_service.addItem("")
        self.client_edit_profile_cmb_service.setObjectName(u"client_edit_profile_cmb_service")
        self.client_edit_profile_cmb_service.setGeometry(QRect(320, 270, 371, 41))
        font1 = QFont()
        self.client_edit_profile_cmb_service.setFont(font1)
        self.client_edit_profile_cmb_service.setStyleSheet(u"font-size: 16px;\n"
"background-color: white;\n"
"color: black;")
        self.stackedWidget.addWidget(self.client_edit_profile)
        self.add_client = QWidget()
        self.add_client.setObjectName(u"add_client")
        self.frame_5 = QFrame(self.add_client)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(20, 30, 711, 391))
        self.frame_5.setStyleSheet(u"background-color: white\n"
"")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.add_client_title = QLabel(self.frame_5)
        self.add_client_title.setObjectName(u"add_client_title")
        self.add_client_title.setGeometry(QRect(20, 10, 671, 51))
        self.add_client_title.setStyleSheet(u"background-color: white;\n"
"color: black;\n"
"font-size: 30px;")
        self.add_client_title.setAlignment(Qt.AlignCenter)
        self.add_client_btn_add = QPushButton(self.frame_5)
        self.add_client_btn_add.setObjectName(u"add_client_btn_add")
        self.add_client_btn_add.setGeometry(QRect(200, 270, 161, 41))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush23 = QBrush(QColor(255, 255, 255, 128))
        brush23.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush23)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush24 = QBrush(QColor(255, 255, 255, 128))
        brush24.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush24)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush25 = QBrush(QColor(255, 255, 255, 128))
        brush25.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush25)
#endif
        self.add_client_btn_add.setPalette(palette7)
        self.add_client_btn_add.setFont(font)
        self.add_client_btn_add.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.add_client_btn_cancel = QPushButton(self.frame_5)
        self.add_client_btn_cancel.setObjectName(u"add_client_btn_cancel")
        self.add_client_btn_cancel.setGeometry(QRect(370, 270, 151, 41))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush26 = QBrush(QColor(255, 255, 255, 128))
        brush26.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush26)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush27 = QBrush(QColor(255, 255, 255, 128))
        brush27.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush27)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush28 = QBrush(QColor(255, 255, 255, 128))
        brush28.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush28)
#endif
        self.add_client_btn_cancel.setPalette(palette8)
        self.add_client_btn_cancel.setFont(font)
        self.add_client_btn_cancel.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.add_client_text_first_name = QLineEdit(self.frame_5)
        self.add_client_text_first_name.setObjectName(u"add_client_text_first_name")
        self.add_client_text_first_name.setGeometry(QRect(200, 110, 321, 41))
        self.add_client_text_first_name.setFont(font)
        self.add_client_text_first_name.setStyleSheet(u"background-color: white;\n"
"color: black;")
        self.add_client_text_last_name = QLineEdit(self.frame_5)
        self.add_client_text_last_name.setObjectName(u"add_client_text_last_name")
        self.add_client_text_last_name.setGeometry(QRect(200, 160, 321, 41))
        self.add_client_text_last_name.setFont(font)
        self.add_client_text_last_name.setStyleSheet(u"background-color: white;\n"
"color: black;")
        self.add_client_cmb_service = QComboBox(self.frame_5)
        self.add_client_cmb_service.addItem("")
        self.add_client_cmb_service.addItem("")
        self.add_client_cmb_service.setObjectName(u"add_client_cmb_service")
        self.add_client_cmb_service.setGeometry(QRect(200, 210, 321, 41))
        self.add_client_cmb_service.setFont(font1)
        self.add_client_cmb_service.setStyleSheet(u"font-size: 16px;\n"
"background-color: white;\n"
"color: black;")
        self.stackedWidget.addWidget(self.add_client)
        self.client_delete = QWidget()
        self.client_delete.setObjectName(u"client_delete")
        self.frame_7 = QFrame(self.client_delete)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(20, 30, 711, 391))
        self.frame_7.setStyleSheet(u"background-color: white\n"
"")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.client_list_delete_label_title = QLabel(self.frame_7)
        self.client_list_delete_label_title.setObjectName(u"client_list_delete_label_title")
        self.client_list_delete_label_title.setGeometry(QRect(20, 10, 671, 51))
        self.client_list_delete_label_title.setStyleSheet(u"background-color: white;\n"
"color: black;\n"
"font-size: 30px;")
        self.client_list_delete_label_title.setAlignment(Qt.AlignCenter)
        self.client_list_delete_btn_main = QPushButton(self.frame_7)
        self.client_list_delete_btn_main.setObjectName(u"client_list_delete_btn_main")
        self.client_list_delete_btn_main.setGeometry(QRect(510, 330, 181, 41))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush29 = QBrush(QColor(255, 255, 255, 128))
        brush29.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush29)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush30 = QBrush(QColor(255, 255, 255, 128))
        brush30.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush30)
#endif
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush31 = QBrush(QColor(255, 255, 255, 128))
        brush31.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush31)
#endif
        self.client_list_delete_btn_main.setPalette(palette9)
        self.client_list_delete_btn_main.setFont(font)
        self.client_list_delete_btn_main.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.client_list_delete_btn_delete = QPushButton(self.frame_7)
        self.client_list_delete_btn_delete.setObjectName(u"client_list_delete_btn_delete")
        self.client_list_delete_btn_delete.setGeometry(QRect(320, 330, 181, 41))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush32 = QBrush(QColor(255, 255, 255, 128))
        brush32.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush32)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush33 = QBrush(QColor(255, 255, 255, 128))
        brush33.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush33)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush34 = QBrush(QColor(255, 255, 255, 128))
        brush34.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush34)
#endif
        self.client_list_delete_btn_delete.setPalette(palette10)
        self.client_list_delete_btn_delete.setFont(font)
        self.client_list_delete_btn_delete.setStyleSheet(u"background-color: #033E63;\n"
"color: white")
        self.client_list_delete_list = QTableView(self.frame_7)
        self.client_list_delete_list.setObjectName(u"client_list_delete_list")
        self.client_list_delete_list.setGeometry(QRect(20, 81, 671, 231))
        self.client_list_delete_enter_id = QLineEdit(self.frame_7)
        self.client_list_delete_enter_id.setObjectName(u"client_list_delete_enter_id")
        self.client_list_delete_enter_id.setGeometry(QRect(220, 330, 91, 41))
        self.client_list_delete_enter_id.setFont(font)
        self.client_list_delete_enter_id.setStyleSheet(u"background-color: white;\n"
"color: black;")
        self.stackedWidget.addWidget(self.client_delete)
        self.delete_client_profile = QWidget()
        self.delete_client_profile.setObjectName(u"delete_client_profile")
        self.frame_6 = QFrame(self.delete_client_profile)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(20, 30, 711, 391))
        self.frame_6.setStyleSheet(u"background-color: white\n"
"")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.stackedWidget.addWidget(self.delete_client_profile)
        self.label_welcome = QLabel(self.centralwidget)
        self.label_welcome.setObjectName(u"label_welcome")
        self.label_welcome.setGeometry(QRect(20, 440, 711, 31))
        self.label_welcome.setStyleSheet(u"font-size: 16px;\n"
"color: white;")
        self.label_welcome.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_welcome.raise_()
        self.stackedWidget.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Client Management App", None))
        self.login_label_header.setText(QCoreApplication.translate("MainWindow", u"Log In", None))
        self.login_text_username.setText(QCoreApplication.translate("MainWindow", u"Username", None))
        self.login_text_password.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.login_btn_Sign_In.setText(QCoreApplication.translate("MainWindow", u"Sign In", None))
        self.login_label_login_denied.setText(QCoreApplication.translate("MainWindow", u"Incorrect Username/Password", None))
        self.label.setText("")
        self.menu_label_title.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.menu_label_header.setText(QCoreApplication.translate("MainWindow", u"Make Selection", None))

        __sortingEnabled = self.menu_list.isSortingEnabled()
        self.menu_list.setSortingEnabled(False)
        ___qlistwidgetitem = self.menu_list.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"DISPLAY client list", None));
        ___qlistwidgetitem1 = self.menu_list.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"EDIT a client", None));
        ___qlistwidgetitem2 = self.menu_list.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u"ADD a new client", None));
        ___qlistwidgetitem3 = self.menu_list.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u"DELETE a client", None));
        ___qlistwidgetitem4 = self.menu_list.item(4)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Exit the program", None));
        self.menu_list.setSortingEnabled(__sortingEnabled)

        self.menu_btn_submit.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.label_2.setText("")
        self.client_list_label_title.setText(QCoreApplication.translate("MainWindow", u"Client List", None))
        self.client_list_btn_main.setText(QCoreApplication.translate("MainWindow", u"Main", None))
        self.client_list_edit_label_title.setText(QCoreApplication.translate("MainWindow", u"Edit Client", None))
        self.client_list_edit_btn_main.setText(QCoreApplication.translate("MainWindow", u"Main", None))
        self.client_list_edit_btn_edit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.client_list_edit_enter_id.setText(QCoreApplication.translate("MainWindow", u"Enter ID", None))
        self.client_edit_profile_title.setText(QCoreApplication.translate("MainWindow", u"Edit Client Selection", None))
        self.client_edit_profile_btn_update.setText(QCoreApplication.translate("MainWindow", u"Update", None))
        self.client_edit_profile_btn_cancel.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.client_edit_profile_first_name.setText(QCoreApplication.translate("MainWindow", u"First Name", None))
        self.client_edit_profile_last_name.setText(QCoreApplication.translate("MainWindow", u"Last Name", None))
        self.client_edit_profile_cmb_service.setItemText(0, QCoreApplication.translate("MainWindow", u"Brokerage", None))
        self.client_edit_profile_cmb_service.setItemText(1, QCoreApplication.translate("MainWindow", u"Retirement", None))

        self.add_client_title.setText(QCoreApplication.translate("MainWindow", u"Add Client", None))
        self.add_client_btn_add.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.add_client_btn_cancel.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.add_client_text_first_name.setText(QCoreApplication.translate("MainWindow", u"First Name", None))
        self.add_client_text_last_name.setText(QCoreApplication.translate("MainWindow", u"Last Name", None))
        self.add_client_cmb_service.setItemText(0, QCoreApplication.translate("MainWindow", u"Brokerage", None))
        self.add_client_cmb_service.setItemText(1, QCoreApplication.translate("MainWindow", u"Retirement", None))

        self.client_list_delete_label_title.setText(QCoreApplication.translate("MainWindow", u"Delete Client", None))
        self.client_list_delete_btn_main.setText(QCoreApplication.translate("MainWindow", u"Main", None))
        self.client_list_delete_btn_delete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.client_list_delete_enter_id.setText(QCoreApplication.translate("MainWindow", u"Enter ID", None))
        self.label_welcome.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
    # retranslateUi
